apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nvariant-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: nvariant-secrets
    creationPolicy: Owner
  data:
    - secretKey: INTERNAL_JWT_SECRET
      remoteRef:
        key: nvariant/prod
        property: INTERNAL_JWT_SECRET
    - secretKey: DATABASE_URL
      remoteRef:
        key: nvariant/prod
        property: DATABASE_URL
