apiVersion: v1
kind: Service
metadata:
  name: control-plane-ui
  namespace: nvariant
spec:
  selector:
    app: control-plane-ui
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: explorer-ui
  namespace: nvariant
spec:
  selector:
    app: explorer-ui
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: canonical-api
  namespace: nvariant
spec:
  selector:
    app: canonical-api
  ports:
    - name: http
      port: 80
      targetPort: 3000
