apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: canonical-api-pdb
  namespace: nvariant
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: canonical-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: control-plane-ui-pdb
  namespace: nvariant
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: control-plane-ui
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: explorer-ui-pdb
  namespace: nvariant
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: explorer-ui
